version: '3'

services:
  datum_api1:
    image: datumdesafioapi1
    build:
      context: ./API_1
    ports:
      - "8080:80"
    networks:
      - desafio-datum_api

  datum_api2:
    image: datumdesafioapi2
    build:
      context: ./API_2
    ports:
      - "8081:80"
    networks:
      - desafio-datum_api

networks: 
    desafio-datum_api:
        driver: bridge